export const Ranking = [
    {
        key:"1",
        rankList: '1',
        userName: "Nguyen Van A",
        userPoint: "12345",
    },
    {
        key:"2",
        rankList: '2',
        userName: "Nguyen Van A",
        userPoint: "1234",
    },
    {
        key:"3",
        rankList: '3',
        userName: "Nguyen Van A",
        userPoint: "1235",
    },
    {
        key:"4",
        rankList: '4',
        userName: "Nguyen Van A",
        userPoint: "1236",
    },
    {
        key:"5",
        rankList: '5',
        userName: "Nguyen Van A",
        userPoint: "1237",
    },
    {
        key:"6",
        rankList: '6',
        userName: "Nguyen Van A",
        userPoint: "1238",
    },
    {
        key:"7",
        rankList: '7',
        userName: "Nguyen Van A",
        userPoint: "1239",
    },
    {
        key:"8",
        rankList: '8',
        userName: "Nguyen Van A",
        userPoint: "1240",
    },
    {
        key:"9",
        rankList: '9',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"10",
        rankList: '10',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"11",
        rankList: '11',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"12",
        rankList: '12',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"13",
        rankList: '13',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"14",
        rankList: '14',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"15",
        rankList: '15',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"16",
        rankList: '16',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
    {
        key:"17",
        rankList: '17',
        userName: "Nguyen Van A",
        userPoint: "1241",
    },
];

